name: coverage-comment

on:
  workflow_run:
    workflows:
      - "test"
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: on artifact
        id: artifact
        uses: marocchino/on_artifact@v1
        with:
          name: all

      - run: curl https://raw.githubusercontent.com/irongut/CodeCoverageSummary/master/src/coverage.simplecov.xml > coverage.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          format: 'markdown'
          output: 'both'

      - name: Store coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            coverage.xml
            code-coverage-results.md

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@3d60a5b2dae89d44e0c6ddc69dd7536aec2071cd
        with:
          recreate: true
          path: code-coverage-results.md
          number: ${{ steps.artifact.outputs.number }}
