name: test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  python-3_9:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 2
    permissions:
      pull-requests: write # for marocchino/sticky-pull-request-comment
    steps:
      - run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} | tee ./pr/number
      - uses: actions/upload-artifact@v2
        with:
          name: all
          path: pr/
