name: test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  python-3_9:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      pull-requests: write # for marocchino/sticky-pull-request-comment
    steps:
    - uses: actions/checkout@v3
    - run: curl https://raw.githubusercontent.com/irongut/CodeCoverageSummary/master/src/coverage.simplecov.xml > coverage.xml

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        format: 'markdown'
        output: 'both'

    - name: Store coverage results
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: |
          coverage.xml
          code-coverage-results.md
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@3d60a5b2dae89d44e0c6ddc69dd7536aec2071cd
      with:
        recreate: true
        path: code-coverage-results.md
